networks:
  laravel:
    driver: bridge
volumes:
    database:

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api_laravel
        restart: unless-stopped
        working_dir: /var/www/
        depends_on:
            - db
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: nginx_laravel
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/production/:/etc/nginx/conf.d/
        networks:
            - laravel

    db:
        image: mysql:8.3.0
        container_name: mysql_laravel
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - database:/var/lib/mysql
        networks:
            - laravel