name: CI-CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Docker
        uses: docker/setup-docker-action@v4

      - name: Run docker compose up
        run: docker compose up -d

      - name: Run tests
        run: |
          docker compose exec app composer pest tests/Feature/e2e/v1/*
          docker compose exec app composer pest tests/Feature/unit/*